### PR TITLE
Added support for South to introspect TimeZoneField

### PR DESCRIPTION
**Pull request by sidmitra**

### CODE REVIEW

**Comment by roberts81** [comment]
+1

**Comment by adamcharnock** [comment]
+1

**Comment by groovecoder** [comment]
+1

**Comment by tuttle** [comment]
+1

**Comment by ghost** [comment]
+1

**Comment by brosner** [comment]
Is this still relevant? If so, can the coding style please be cleaned up? See existing coding style.

**Comment by groovecoder** [comment]
Still relevant for sure.

**Comment by ogirardot** [comment]
+1

**Comment by chrischambers** [comment]
+1

**Comment by playpauseandstop** [comment]
+1

**Pull request closed without merging**
